key_bindings:
  - { key: T, mods: Control|Shift, action: SpawnNewInstance }

# Ubuntu Mono (Nerd patch) seems to be the closest to Bront which is wrongly
# patched
font:
  size: 15
  normal:
    #family: "JetBrainsMono Nerd Font"
    #    family: "Bront Nerd Font"
    #family: "DejaVuSans Mono Nerd Font Mono"
    #style: "Book"
    family: "UbuntuMono Nerd Font Mono"
    style: "Regular"
  bold:
    #    family: "JetBrainsMono Nerd Font"
    #    style: "Medium"
    family: "UbuntuMono Nerd Font Mono"
    style: "Regular"

colors:
  # Cursor colors
  cursor:
    text: "0xFFFFFF"
    cursor: "0xe91e63"
  vi_mode_cursor:
    text: "0xFFFFFF"
    cursor: "0xffa500"

  # Default colors
  primary:
    background: "0x32374d"
    foreground: "0xd0d0d0"

  # Normal colors
  normal:
    black: "0x263238"
    red: "0xff9800"
    green: "0x8bc34a"
    yellow: "0xffc107"
    blue: "0x03a9f4"
    magenta: "0xe91e63"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"
