shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
key_bindings:
  # - { key: T, mods: Control|Shift, action: SpawnNewInstance }
  # tmux keybindings (obtained via `xxd -ps`)
  - { key: T, mods: Command, chars: "\x02\x63" }
#   - { key: Key1, mods: Command, chars: "\x02\x31" }
#   - { key: Key2, mods: Command, chars: "\x02\x32" }
#   - { key: Key3, mods: Command, chars: "\x02\x33" }
#   - { key: Key4, mods: Command, chars: "\x02\x34" }
#   - { key: Key5, mods: Command, chars: "\x02\x35" }
#   - { key: Key6, mods: Command, chars: "\x02\x36" }
#   - { key: Key7, mods: Command, chars: "\x02\x37" }
#   - { key: Key8, mods: Command, chars: "\x02\x38" }
#   - { key: Key9, mods: Command, chars: "\x02\x39" }
#   - { key: W, mods: Command, chars: "\x02\x78" }
#   - { key: V, mods: Command, chars: "\x02\x25" }
#   - { key: S, mods: Command, chars: "\x02\x22" }
#   - { key: J, mods: Command, chars: "\x02\x6a" }
#   - { key: L, mods: Command, chars: "\x02\x6c" }
#   - { key: K, mods: Command, chars: "\x02\x6b" }
# # Needs https://github.com/alacritty/alacritty/issues/5346#issuecomment-1055695103
#   - { key: H, mods: Command, chars: "\x02\x68" }

# 1b5b44
# 021b5b440



window:
  padding:
    x: 2
    y: 5
  dynamic_padding: false
  dynamic_title: false
  decorations: buttonless
  opacity: 0.65
  dimensions:
    columns: 250
    lines: 65

# Ubuntu Mono (Nerd patch) seems to be the closest to Bront which is wrongly
# patched
font:
  size: 18
  normal:
    #family: "JetBrainsMono Nerd Font"
    #    family: "Bront Nerd Font"
    #family: "DejaVuSans Mono Nerd Font Mono"
    #style: "Book"
    # family: "UbuntuMono Nerd Font Mono"
    # style: "Regular"
    # family: "MesloLGS NF"
    family: "DroidSansMono Nerd Font"
    style: "Regular"
  bold:
    #    family: "JetBrainsMono Nerd Font"
    #    style: "Medium"
    # family: "UbuntuMono Nerd Font Mono"
    # style: "Regular"
    # family: "MesloLGS NF"
    family: "DroidSansMono Nerd Font"
    style: "Bold"

# colors:
#     # Default colors
#     primary:
#         background: "#303446" # base
#         foreground: "#C6D0F5" # text
#         # Bright and dim foreground colors
#         dim_foreground: "#C6D0F5" # text
#         bright_foreground: "#C6D0F5" # text

#     # Cursor colors
#     cursor:
#         text: "#303446" # base
#         cursor: "#F2D5CF" # rosewater
#     vi_mode_cursor:
#         text: "#303446" # base
#         cursor: "#BABBF1" # lavender

#     # Search colors
#     search:
#         matches:
#             foreground: "#303446" # base
#             background: "#A5ADCE" # subtext0
#         focused_match:
#             foreground: "#303446" # base
#             background: "#A6D189" # green
#         footer_bar:
#             foreground: "#303446" # base
#             background: "#A5ADCE" # subtext0

#     # Keyboard regex hints
#     hints:
#         start:
#             foreground: "#303446" # base
#             background: "#E5C890" # yellow
#         end:
#             foreground: "#303446" # base
#             background: "#A5ADCE" # subtext0

#     # Selection colors
#     selection:
#         text: "#303446" # base
#         background: "#F2D5CF" # rosewater

#     # Normal colors
#     normal:
#         black: "#51576D" # surface1
#         red: "#E78284" # red
#         green: "#A6D189" # green
#         yellow: "#E5C890" # yellow
#         blue: "#8CAAEE" # blue
#         magenta: "#F4B8E4" # pink
#         cyan: "#81C8BE" # teal
#         white: "#B5BFE2" # subtext1

#     # Bright colors
#     bright:
#         black: "#626880" # surface2
#         red: "#E78284" # red
#         green: "#A6D189" # green
#         yellow: "#E5C890" # yellow
#         blue: "#8CAAEE" # blue
#         magenta: "#F4B8E4" # pink
#         cyan: "#81C8BE" # teal
#         white: "#A5ADCE" # subtext0

#     # Dim colors
#     dim:
#         black: "#51576D" # surface1
#         red: "#E78284" # red
#         green: "#A6D189" # green
#         yellow: "#E5C890" # yellow
#         blue: "#8CAAEE" # blue
#         magenta: "#F4B8E4" # pink
#         cyan: "#81C8BE" # teal
#         white: "#B5BFE2" # subtext1

#     indexed_colors:
#         - { index: 16, color: "#EF9F76" }
#         - { index: 17, color: "#F2D5CF" }

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
  footer_bar:
    background: '#282a36'
    foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow:  '0xecbe7b'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
